const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"店家管理",
			            "menuJump":"列表",
			            "tableName":"shangjia"
			        }
			    ],
			    "menu":"店家管理"
			}
			   ,{
			       "child":[
			           {
			               "buttons":[
			                   "查看",
			                   "新增",
			                   "修改",
			                   "删除"
			               ],
			               "menu":"用户管理",
			               "menuJump":"列表",
			               "tableName":"yonghu"
			           }
			       ],
			       "menu":"用户管理"
			   }
				,{
					"child":[
						{
							"buttons":[
								"查看",
								"新增",
								"修改",
								"删除"
							],
							"menu":"商品管理",
							"menuJump":"列表",
							"tableName":"shangpin"
						}
						,
						{
							"buttons":[
								"查看",
								"修改",
								"删除"
							],
							"menu":"商品评价管理",
							"menuJump":"列表",
							"tableName":"shangpinCommentback"
						}
						,
						{
							"buttons":[
								"查看",
								"删除"
							],
							"menu":"商品收藏管理",
							"menuJump":"列表",
							"tableName":"shangpinCollection"
						}
						,
						{
							"buttons":[
								"订单",
								"查看",
								"报表",
								"删除"
							],
							"menu":"商品订单管理",
							"menuJump":"列表",
							"tableName":"shangpinOrder"
						}
					],
					"menu":"商品管理"
				}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"广告管理",
                        "menuJump":"列表",
                        "tableName":"guanggao"
                    }
                ],
                "menu":"广告管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"广告类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryGuanggao"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"资讯类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryNews"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"店家类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryShangjia"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"商品类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryShangpin"
			        }
			    ],
			    "menu":"基础数据管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"论坛管理",
			            "menuJump":"列表",
			            "tableName":"forum"
			        }
			    ],
			    "menu":"论坛管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"菜品资讯管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"菜品资讯管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
            /*,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"数据备份",
			            "menuJump":"列表",
			            "tableName":"beifen"
			        },
					{
					    "buttons":[
					        "查看"
					    ],
					    "menu":"数据还原",
					    "menuJump":"列表",
					    "tableName":"huanyuan"
					}
			    ],
			    "menu":"数据库管理"
			}*/
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
	{
	    "backMenu":[
	        {
					"child":[
						{
							"buttons":[
								"查看",
								"新增",
								"修改",
								"删除"
							],
							"menu":"商品管理",
							"menuJump":"列表",
							"tableName":"shangpin"
						}
						,
						{
							"buttons":[
								"查看",
								"修改",
								"删除"
							],
							"menu":"商品评价管理",
							"menuJump":"列表",
							"tableName":"shangpinCommentback"
						}
						,
						{
							"buttons":[
								"查看"
							],
							"menu":"商品收藏管理",
							"menuJump":"列表",
							"tableName":"shangpinCollection"
						}
						,
						{
							"buttons":[
								"订单",
								"查看",
								"删除"
							],
							"menu":"商品订单管理",
							"menuJump":"列表",
							"tableName":"shangpinOrder"
						}
					],
					"menu":"商品管理"
				}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
							"新增",
							"修改",
							"删除"
	                    ],
	                    "menu":"广告管理",
	                    "menuJump":"列表",
	                    "tableName":"guanggao"
	                }
	            ],
	            "menu":"广告管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除"
			            ],
			            "menu":"论坛管理",
			            "menuJump":"列表",
			            "tableName":"forum"
			        }
			    ],
			    "menu":"论坛管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"菜品资讯管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"菜品资讯管理"
	        }
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"店家",
	    "tableName":"shangjia"
	}
]
    }
}
export default menu;
